name: Production workflow


on:
  push:
    branches:
      - master


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - run: npm install
      - run: npm run build --if-present
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3 12.12
        with:
          args: deploy --dir=build --prod
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: 'algorium'
          heroku_email: 'wiktor.waj@gmail.com'
